name : my first workflow

on: push

jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - run: echo "Building app"
 test:
 runs-on: ubuntu-latest
 needs: build # This job runs **after** build
 steps:
 - run: echo "Running tests"
